/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Iphone iphone = new Iphone("iphone1","red","apple");
        iphone.call("hahha");
        System.out.println(iphone.toString());
        Person p =new Person("jack", iphone);
        p.sendMessage("ddddddddddddd");
    }
}
